### ISSUE TITLE
Add tag for the fixed revision

### ISSUE THREAD

**Issue by masterada** [josselin-c/go.uuid#8]
I suggest adding 2.0.1 tag (2.0 to note the breaking change originally introduced in satori 1.2 version, and 0.1 to note the security patch).

**Comment by josselin-c** [comment]
I have forked this from satori/go.uuid to create https://github.com/satori/go.uuid/pull/75
I'm not commited to maintain this fork. You should instead look at alternatives such as github.com/google/uuid or https://github.com/kevinburke/go.uuid for alternatives!

**Comment by theckman** [comment]
To throw our name in the ring: https://github.com/gofrs/uuid -- it's forked from the same repo. Some people in the Go community have come together to support it.
